## Configuracion de Spring
spring:
  application:
    name: ms-store-products

## Configuracion de Instancia
server:
  port: 8081
  fullAddress: ${HOST:http://localhost}:${PORT:${server.port}}

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8083/eureka}
  instance:
    preferIpAddress: true # For local development. Set to false if you want to use the hostname in a DNS-enabled environment
    hostname: ${HOSTNAME:localhost}

##Elasticsearch config
elasticsearch:
  host: ${ELASTICSEARCH_HOST}
  credentials:
    user: ${ELASTICSEARCH_USER}
    password: ${ELASTICSEARCH_PWD}
logging:
  level:
    tracer: TRACE